//constructor(id, nivel, tipo, status, nombres, apellidos, sexo, nace, muere, detalle, url, foto)
const integrantes = [
  new Familiar('01', 1, 'f', 'd', 'Euro Vicente', "de la Torre Rincón", 'm', '28-octubre', '31-enero', true, '-', false), 
  new Familiar('01a', 1, 'f', 'd', 'Carmen', "Campos", 'f', '', '', false, '-', '.jpg'), 
  new Familiar('011', 2, 'f', 'c', 'Euro Vicente', "D' La Torre Campos", 'm', '24-mayo', '', true, '-', false), 
  new Familiar('011a', 2, 'p', 'c', 'Cora', "Ochoa", 'f', '24-mayo', '', false, '-', false), 
  new Familiar('0111', 3, 'f', 'r', 'Euro Guillermo', "D' La Torre Ochoa", 'm', '17-noviembre', '', false, '-', false), 
  new Familiar('0112', 3, 'f', 'c', 'Coralibeth', "D' La Torre Ochoa", 'f', '', '', true, '-', false), 
  new Familiar('0112a', 3, 'p', 'c', 'Orlando', "Mercado", 'm', '', '', false, '-', false), 
  new Familiar('01121', 4, 'f', 's', 'David', "Mercado D' La Torre", 'm', '', '', false, '-', false), 
  new Familiar('01122', 4, 'f', 's', 'Mateo', "Mercado D' La Torre", 'm', '', '', false, '-', false), 
  new Familiar('0113', 3, 'f', 's', 'Euro César', "D' La Torre Ochoa", 'm', '', '', false, '-', false), 
  new Familiar('012', 2, 'f', 'v', 'Carmen Sofía', "de la Torre Campos", 'f', '30-marzo', '', true, '-', '.jpg'), 
  new Familiar('012a', 2, 'p', 'd', 'Oscar', "Gudiño", 'm', '', '', false, '-', false), 
  new Familiar('0121', 3, 'f', 'c', 'Oscar Eduardo', "Gudiño de la Torre", 'm', '06-abril', '', true, '-', false), 
  new Familiar('0121a', 3, 'p', 'c', 'Andreína', "Rodríguez", 'f', '05-julio', '', false, '-', false), 
  new Familiar('01211', 4, 'f', 's', 'Anastassia Sofía', "Gudiño Rodríguez", 'f', '25-julio', '', false, '-', false), 
  new Familiar('0122', 3, 'f', 'c', 'Oscar Enrique', "Gudiño de la Torre", 'm', '30-noviembre', '', true, '-', false), 
  new Familiar('0122a', 3, 'p', 'c', 'Rohelly', "Dominguez", 'f', '30-septiembre', '', false, '-', false), 
  new Familiar('01221', 4, 'f', 's', 'Enrique Ignacio', "Gudiño Domínguez", 'm', '24-febrero', '', false, '-', false), 
  new Familiar('01212', 4, 'f', 's', 'Vicente Enrique', "Gudiño Domínguez", 'm', '28-abril', '', false, '-', false), 
  new Familiar('013', 2, 'f', 'c', 'Gerardo', "de la Torre Campos", 'm', '17-agosto', '', true, '-', false), 
  new Familiar('013a', 2, 'p', 'c', 'Morella', "Bolívar", 'f', '02-marzo', '', false, '-', false), 
  new Familiar('0131', 3, 'f', 'c', 'Euro Alejandro', "de la Torre Bolívar", 'm', '', '', true, '-', false), 
  new Familiar('0131a', 3, 'p', 'c', 'Rose-Marie ', "Vallee", 'f', '', '', false, '-', false), 
  new Familiar('01311', 4, 'f', 'c', 'Carmen Emilia', "de la Torre Vallee", 'f', '', '', false, '-', false), 
  new Familiar('0132', 3, 'f', 's', 'Fernando André', "de la Torre Bolívar", 'm', '', '', false, '-', false), 
  new Familiar('0133', 3, 'f', 's', 'Diego Emiliano', "de la Torre Bolívar", 'm', '', '', false, '-', false), 
  new Familiar('014', 2, 'f', 'c', 'Carolina', "de la Torre Campos", 'f', '04-octubre', '', true, '-', false), 
  new Familiar('014a', 2, 'p', 'c', 'Phanor', "Viera", 'm', '08-enero', '', false, '-', false), 
  new Familiar('0141', 3, 'f', 'c', 'Olivier', "Viera de la Torre", 'm', '12-mayo', '', true, '-', false), 
  new Familiar('0141a', 3, 'f', 'c', 'Aniuska Isabel', "Avendaño", 'f', '', '', false, '-', false), 
  new Familiar('01411', 4, 'f', 'c', 'Samuel David', "Viera Avendaño", 'm', '', '', false, '-', false), 
  new Familiar('01412', 4, 'f', 'c', 'Sara Gabriela', "Viera Avendaño", 'f', '', '', false, '-', false), 
  new Familiar('0142', 3, 'f', 'c', 'Adrián Alberto', "Viera de la Torre", 'm', '14-mayo', '', false, '-', false), 
  new Familiar('0142a', 3, 'p', 'c', 'Jade', "Tinio", 'f', '', '', false, '-', false), 
  new Familiar('0143', 3, 'f', 's', 'Andrew', "Viera de la Torre", 'm', '17-abril', '', false, '-', false), 
  new Familiar('0144', 3, 'f', 's', 'Karen Andrea', "Viera de la Torre", 'f', '30-octubre', '', false, '-', false),
    ]
